name: oneplayer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  safemap: ^2.1.0
  tapped: ^2.0.0
  video_player: ^2.8.2
  video_player_media_kit: ^1.0.6
  # 媒体库依赖
  media_kit_libs_android_video: ^1.3.6
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.9
  media_kit_libs_linux: ^1.1.3
  flutter_vlc_player: ^7.4.3
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_macos_video: ^1.1.4
  window_size: ^0.1.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
