name: oneplayer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  safemap: ^2.1.0
  tapped: ^2.0.0
  video_player: ^2.9.5
  flutter_vlc_player: ^7.4.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
